import Link from "next/link"
import Head from "next/head"
import Image from "next/image"

const Layout = ({children, title='cryptocurrency price tracker'}) => {
    return (
        <div className="layout">
            <Head>
             <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
          <Link href="/" passHref>
              <a>
                <Image src='/../public/vercel.svg' alt="crypto tracker" width={100} height={100}/>
              </a>
          </Link>
      </header>
      <main>{children}</main>
        </div>
    )
}

export default Layout
