import Head from 'next/head'
import {useState} from 'react'
import CoinList from '../components/CoinList'
import Layout from '../components/Layout'
import SearchBar from '../components/SearchBar'
//import styles from '../styles/Home.module.css'

export default function Home ({availableCoins}) {
  const [search, setSearch] = useState('');

  const allCoins = availableCoins.filter(coin =>
    coin.name.toLowerCase().includes(search.toLowerCase())
  );
  
  
  const handleChange = e =>{
    e.preventDefault();

    setSearch(e.target.value.toLowerCase());
  };
   
  return (
    <Layout>
      <div className='container'>
      <Head>
        <title>Crypto currency price tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="coinApp">
        <h2>This is crypto tracker</h2>
           <SearchBar type='text' placeholder='Search' onChange={handleChange}/>
           {/* <CoinList availableCoins ={allCoins} /> */}
           <CoinList availableCoins={allCoins}/>
        </div>
    </div>
    </Layout>
  )
    
}


export const getServerSideProps = async () =>{
  const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=10&page=1&sparkline=false');

  const availableCoins = await res.json();
  return{
    props:{
      availableCoins
    }
  };
};